apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeception-operator
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/component: rbac
    {{- include "kubeception-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cluster.kubeception.ulfo.fr
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeception-operator
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/component: rbac
    {{- include "kubeception-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeception-operator
subjects:
- kind: ServiceAccount
  name: kubeception-operator
  namespace: {{ .Release.Namespace }}
