# Default values for kubeception-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
controller:
  replicas: 1
  image:
    repository: elssuy/kubeception-operator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.2-alpha"

  imagePullSecrets: []

  podAnnotations: {}

  resources: 
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  securityContext: 
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  nodeSelector: {}

  tolerations: []

  affinity: {}

cert-manager:
  enabled: true
  installCRDs: true
